name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
          cache: "pip"
      - name: "Install Poetry"
        run: pipx install poetry
      - name: "Install dependencies"
        run: poetry install
      - name: "Ruff checks"
        continue-on-error: true
        run: poetry run ruff check . --output-format=full --diff
      - name: "Format check"
        continue-on-error: true
        run: poetry run ruff format . --check --diff
      - name: "Mypy"
        continue-on-error: true
        run: poetry run mypy
      - name: "Pytest"
        run: PYTHONPATH=. poetry run pytest -v -m ci
